### ISSUE TITLE
Download accelerator Multiget

### ISSUE THREAD

**Issue by talesam** [jorgicio/jorgicio-gentoo#10]
There is an ebuild this app, but neither has the layman and I trust more in your repository, you could create on your own? :)

https://github.com/lvming/gentoo-overlay/blob/master/net-misc/multiget/multiget-1.2.0.ebuild

**Comment by jorgicio** [comment]
Well, sounds good. The code is a little bit abandoned, but there's an alpha version (2.0) from 2013. Let me try and tell you later.

**Comment by jorgicio** [comment]
The ebuild is up. Try it and tell me how it goes.

**Comment by talesam** [comment]
Wow, you're fast! I will test now and tell you !! Thank U !! ;)

**Comment by talesam** [comment]
I have problems to unmask the package, as he added in package.unmask, but still ignoring.

See:

neit package.unmask # emerge -av net-misc/multiget

 * IMPORTANT: 4 config files in '/etc/portage' need updating.
 * See the CONFIGURATION FILES section of the emerge
 * man page to learn how to update config files.

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    *] net-misc/multiget-2.0_alpha::jorgicio  320 KiB

Total: 1 package (1 new), Size of downloads: 320 KiB

The following keyword changes are necessary to proceed:
 (see "package.accept_keywords" in the portage(5) man page for more details)
# required by net-misc/multiget (argument)
=net-misc/multiget-2.0_alpha **

NOTE: The --autounmask-keep-masks option will prevent emerge
      from creating package.unmask or ** keyword changes.

Would you like to add these changes to your config files? [Yes/No] 

Autounmask changes successfully written.

 * IMPORTANT: 5 config files in '/etc/portage' need updating.
 * See the CONFIGURATION FILES section of the emerge
 * man page to learn how to update config files.

!!! The following installed packages are masked:
- www-client/google-chrome-39.0.2171.95_p1::gentoo (masked by: google-chrome license(s))
A copy of the 'google-chrome' license is located at '/usr/portage/licenses/google-chrome'.

- www-plugins/adobe-flash-11.2.202.425::gentoo (masked by: AdobeFlash-11.x license(s))
A copy of the 'AdobeFlash-11.x' license is located at '/usr/portage/licenses/AdobeFlash-11.x'.

- www-plugins/google-talkplugin-5.38.6.0::gentoo (masked by: Google-TOS license(s))
A copy of the 'Google-TOS' license is located at '/usr/portage/licenses/Google-TOS'.

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.

neit package.unmask #

**Comment by jorgicio** [comment]
Well... I knew what happened... Ebuild upgraded. Try again. Also, look at your (un)mask files.

**Comment by talesam** [comment]
Error...

http://pastebin.com/qqcQ5GFK

**Comment by jorgicio** [comment]
As I noticed, this package it seems somewhat deprecated and has no maintenance since some time ago.
