### ISSUE TITLE
net-misc/megasync-3.0.1.0::jorgicio can't download meganz-sdk-3.1.4.tar.gz

### ISSUE THREAD

**Issue by YangMame** [jorgicio/jorgicio-gentoo#103]
log : https://paste.pound-python.org/show/ha2tljenwu9TlLtq9e1l/
thanks !

**Comment by jorgicio** [comment]
Fixed. Please try again and tell me what's going on.

**Comment by YangMame** [comment]
@jorgicio failed again
and the log : https://paste.pound-python.org/show/vNbt5MXE6Reb6rHsBnbd/
thanks !

**Comment by jorgicio** [comment]
Got it. I hope the fix just submitted works now. Resync and try again.

**Comment by YangMame** [comment]
Succeeded Thank You !

**Comment by jorgicio** [comment]
You're welcome!
