### ISSUE TITLE
x11-themes/adapta-gtk-theme-9999 needs dev-lang/sassc to merge

### ISSUE THREAD

**Issue by Althorion** [jorgicio/jorgicio-gentoo#104]
`dev-lang/sassc` should be a build dependency of `x11-themes/adapta-gtk-theme-9999`. Without it, emerging `x11-themes/adapta-gtk-theme-9999` fails with following error:
```
checking for sassc... no
configure: error: 'sassc' not found.
```

**Comment by jorgicio** [comment]
Fixed. Please, try again. Also, I bumped a recent version.

**Comment by jorgicio** [comment]
As I noted the issue is the compiler sassc was not found and now that's working, I'll close this issue.
