### ISSUE TITLE
sdlmame: build failure

### ISSUE THREAD

**Issue by Techwolf** [jorgicio/jorgicio-gentoo#112]
Current ebuild will fail with "Fatal error: can't create ../../../../linux_gcc/obj/x64/Release/generated/version.o: No such file or directory"

The fix I did was to "export QT_SELECT=qt5" before doing the emerge.

I had to add QT_SELECT=qt5 to another ebuild of mine due to it defaulted to qt4 and called the wrong program.

I have not dug into the code to figure out the root cause. This ebuild takes up an hour to build plus chews up 15G of RAM during the link stage.

**Comment by jorgicio** [comment]
Did you build the package with USE="debug" enabled? If so, this may give you that error you mentioned. 
Thanks for the advice.

**Comment by Techwolf** [comment]
I do have split debug enabled and -gddb.

**Comment by jorgicio** [comment]
Ok, this may explain some things... I'll fix it then.

**Comment by Techwolf** [comment]
Another note, I do not have any USE debug flags set.

**Comment by jorgicio** [comment]
Ok, I got it. Anyways, I added the variable you mentioned somewhere in the ebuild. As I watched in the .ebuild, the qt functions and variables are used only if USE="debug" is set, as well as its dependencies.
