### ISSUE TITLE
Eselect Repository as replacement for Layman in readme

### ISSUE THREAD

**Issue by NHOrus** [jorgicio/jorgicio-gentoo#118]
See https://wiki.gentoo.org/wiki/Eselect/Repository

**Comment by jorgicio** [comment]
Thanks, I didn't know about this new feature, so I'm trying this now.

README updated.

**Comment by NHOrus** [comment]
Works, works not worse than Layman and more integrated into general eselect/portage gentoo infrastructure. I also learned about it from Gentoo IRC, but it thankfully mentioned in handbook.
