### ISSUE TITLE
visual-studio-code : libnss3.so not found 

### ISSUE THREAD

**Issue by gronono** [jorgicio/jorgicio-gentoo#126]
Hi,

I've installed app-editors/visual-studio-code-1.22.2:

> $ visual-studio-code
> /opt/visual-studio-code/bin/../code: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

Dependency "dev-libs/nss" is missing in the ebuild file.

And if I can ask a question: why I need cups for visual studio code ? There is a way to add 'cups' use flag to enable / disable it ?

Thanks a lot for the visual-studio-code ebuild.

**Comment by jorgicio** [comment]
Done. I hope it helps.
And I can't remember and don't know why cups is necessary, so I removed it.

**Comment by gronono** [comment]
I'm sorry about cups. Visual Studio Code needs libcups.so.2.
Thanks.

**Comment by gronono** [comment]
Thank you
