### ISSUE TITLE
Changes in Haguichi 1.4.0

### ISSUE THREAD

**Issue by ztefn** [jorgicio/jorgicio-gentoo#128]
Hello Jorge!

Haguichi 1.4.0 [is out](https://www.haguichi.net/news/release140/) and there are some packaging changes you should know about.

Most importantly, haguichi-indicator is no longer provided as a separate package, but instead build right into Haguichi now as [build option](https://github.com/ztefn/haguichi/blob/master/INSTALL.md#build-options) (`-Denable-appindicator=true`). Because the D-Bus name change to `com.github.ztefn.haguichi` the old haguichi-indicator package will stop working starting with version 1.4.0 and has already stopped working with the git version a while ago.

Additionally, some [dependencies](https://github.com/ztefn/haguichi/blob/master/INSTALL.md#dependencies) got a slight minimum required version bump: Vala (>= 0.30), GLib (>= 2.48) and GTK+ (>= 3.18).

If you have any questions just let me know!

**Comment by jorgicio** [comment]
Hello, @ztefn, thanks for the announcement.
Just one question: in the Haguichi page, it says it's licensed by GPLv3+, but in the Github repo it says GPLv3. What I'm going to use?

**Comment by ztefn** [comment]
> Copyright © 2007–2018 Stephen Brandt
>
> Haguichi is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, **either version 3 of the License, or (at your option) any later version.**

This means GPLv3+

I guess GitHub's license detection is not so precise :)

**Comment by jorgicio** [comment]
Done. Thank you and have a nice day ;)
