### ISSUE TITLE
missing bfq patches from gentoo-sources 3.19 in ck-sources 3.19

### ISSUE THREAD

**Issue by occ1701** [jorgicio/jorgicio-gentoo#13]
Dear jorgicio,

I'm amazed about your always up to date ck-sources effort !
Thank you very much!

A noob question maybe:
What useflag do I need to use to activate the BFQ patches in the 3.19 kernel? On gentoo-sources they are included with the "experimental" useflag in 3.19. Somehow I am clueless how to activate them in ck-sources 3.19 though.

Thank you very much indeed.

**Comment by jorgicio** [comment]
Hi, you! Thanks to you for you comment!
Being ck-sources, BFQ and BFS patches are included, so there's no need to do something else. However, you need to activate it from the menuconfig.
If you use genkernel, call it with the --menuconfig option.

Also, you need to add the option to the kernel line in the GRUB config file:
elevator=bfq

Try this, and tell me how it went.

Greetings!

**Comment by jorgicio** [comment]
Hi! I found what happened:

Indeed, as you said, BFQ patches are missing, and I don't know why, so I'll test here. If everything is going on well, I'll upgrade.

**Comment by jorgicio** [comment]
Hi again!

I noticed that ck-sources only includes the BFS patches. Sorry for the inconvenience.

However, you can patch the sources by yourself once it's installed in /usr/src/linux. Patches are in: https://pf.natalenko.name/mirrors/bfq/ and use the one according to your kernel.
Or use the pf-sources. It has both.

Sorry again :)

**Comment by occ1701** [comment]
Thank you jorgicio for your quick response !

I wasn't aware either that BFQ patches are not included in the latest ck-sources anymore. Will patch myself then as you suggested, or make the jump to 4.0 as - thanks to you - the latest BFS patches are already included and BFQ patches are already in the testing.

Also had thought about using the pf-sources in the past, but they do not include the gentoo-patch-sets, that are updated more often in point releases, than all the rest.

Thank you again for your kind help !

**Comment by jorgicio** [comment]
You're welcome!

Also, I did my own BFQ patches based on 3.18 and 3.19. There's no much change than the number version. I tried by myself, and it works in ck-sources 4.0.0. Give a try, and tell me how it went, or wait for the official ones: https://www.dropbox.com/sh/efjsnpi58lgehob/AAB8H5BMXLLOcCHkjk3vQDA3a?dl=0
:)

**Comment by jorgicio** [comment]
As I don't maintain this package anymore, I'll close this.
