### ISSUE TITLE
media-libs/zita-resampler 404's, or does not build.

### ISSUE THREAD

**Issue by jason-oliveira** [jorgicio/jorgicio-gentoo#133]
both ebuilds in media-libs/zita-resampler aren't building. The ebuild marked "stable" is 404'ing, as the package was deleted from the host website. The 1.6.0 version does not build. 

audio-overlay has a (working) ebuild for zita-resampler, so you can either opt to delete it, or just use their ebuild.

**Comment by jorgicio** [comment]
That's weird, I just tried rebuilding the 1.6.0 version here and it's working.
Please attach a full log to check it. And I'll remove the 1.3.0 version then.

**Comment by jorgicio** [comment]
Also: As you mentioned the package in audio-overlay is working, I'll use that ebuild then.
