### ISSUE TITLE
net-libs/libqtelegram-ae-10.0.0 build fails, stdlib.h: No such file or directory

### ISSUE THREAD

**Issue by prototype99** [jorgicio/jorgicio-gentoo#134]
[build.log](https://github.com/jorgicio/jorgicio-gentoo/files/2039982/build.log)
i looked into it a bit, and i see replacing some sort of -isystem argument with a simple -I may help

**Comment by jorgicio** [comment]
I noted that you use gcc 8.1.0, which is masked by architecture (how did you unmask it xD), I'm using the stable 6.4.0 and it builds fine. But yes, the -I may help. I'll check it then.

**Comment by prototype99** [comment]
yeah this is... since gcc 6 as far as i can tell? don't worry about my cutting edge gcc i don't get cut much on that edge XD i'll check it when it's done
