### ISSUE TITLE
x11-themes/moka-icon-theme and x11-themes/faba-icon-theme have * as keyword

### ISSUE THREAD

**Issue by simonvanderveldt** [jorgicio/jorgicio-gentoo#135]
Hi Jorge,

Just noticed the ebuilds for `x11-themes/moka-icon-theme` and `x11-themes/faba-icon-theme` have `*` as keyword for the versioned (non-9999) ebuilds. AFAIK `*` shouldn't be used in ebuilds, see https://devmanual.gentoo.org/keywording/.

Since these are releases `~` is probably a better fit. What do you think?

**Comment by jorgicio** [comment]
I think you're right and that's my bad. If you find another package with that, please report it.
Thank you.
I'll fix this issue now.

**Comment by simonvanderveldt** [comment]
Thanks for the quick fix!
