### ISSUE TITLE
failed download ambiance-radiance-flat-colors-suite

### ISSUE THREAD

**Issue by loverdrive** [jorgicio/jorgicio-gentoo#14]
Hi, i add your overlay in my system, but when i try to install radiance ebuild, it gives me this error:

>>> Emerging (1 of 1) x11-themes/ambiance-radiance-flat-colors-suite-14.04.1::jorgicio
>>> Renaming distfile with size 37914 (smaller than PORTAGE_FETCH_RESUME_MIN_SIZE)
Refetching... File renamed to '/usr/portage/distfiles/Ambiance%26Radiance-FLAT-ColorSuite-14-04-1a-LTS.tar.gz._checksum_failure_.fpkerv'

>>> Downloading 'http://distfiles.gentoo.org/distfiles/Ambiance%26Radiance-FLAT-ColorSuite-14-04-1a-LTS.tar.gz'
--2015-05-05 14:38:20--  http://distfiles.gentoo.org/distfiles/Ambiance%26Radiance-FLAT-ColorSuite-14-04-1a-LTS.tar.gz
Resolving distfiles.gentoo.org... 156.56.247.195, 216.165.129.135, 137.226.34.42, ...
Connecting to distfiles.gentoo.org|156.56.247.195|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-05-05 14:38:20 ERROR 404: Not Found.

>>> Downloading 'http://download1299.mediafire.com/2olc1susxv8g/n084cio1n4sityh/Ambiance%26Radiance-FLAT-ColorSuite-14-04-1a-LTS.tar.gz'
--2015-05-05 14:38:20--  http://download1299.mediafire.com/2olc1susxv8g/n084cio1n4sityh/Ambiance%26Radiance-FLAT-ColorSuite-14-04-1a-LTS.tar.gz
Resolving download1299.mediafire.com... 205.196.122.240
Connecting to download1299.mediafire.com|205.196.122.240|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.mediafire.com/download_repair.php?dkey=2olc1susxv8&qkey=n084cio1n4sityh [following]
--2015-05-05 14:38:21--  http://www.mediafire.com/download_repair.php?dkey=2olc1susxv8&qkey=n084cio1n4sityh
Resolving www.mediafire.com... 205.196.120.8, 205.196.120.6
Connecting to www.mediafire.com|205.196.120.8|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/usr/portage/distfiles/Ambiance%26Radiance-FLAT-ColorSuite-14-04-1a-LTS.tar.gz’

/usr/portage/distfi     [  <=>                 ]  37,03K   131KB/s   in 0,3s   

2015-05-05 14:38:21 (131 KB/s) - ‘/usr/portage/distfiles/Ambiance%26Radiance-FLAT-ColorSuite-14-04-1a-LTS.tar.gz’ saved [37914]

!!! Fetched file: Ambiance%26Radiance-FLAT-ColorSuite-14-04-1a-LTS.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      37914
!!! Expected: 9589323
Refetching... File renamed to '/usr/portage/distfiles/Ambiance%26Radiance-FLAT-ColorSuite-14-04-1a-LTS.tar.gz._checksum_failure_.vk47dz'

!!! Couldn't download 'Ambiance%26Radiance-FLAT-ColorSuite-14-04-1a-LTS.tar.gz'. Aborting.
 * Fetch failed for 'x11-themes/ambiance-radiance-flat-colors-suite-14.04.1', Log file:
 *  '/var/tmp/portage/x11-themes/ambiance-radiance-flat-colors-suite-14.04.1/temp/build.log'

>>> Failed to emerge x11-themes/ambiance-radiance-flat-colors-suite-14.04.1, Log file:

>>>  '/var/tmp/portage/x11-themes/ambiance-radiance-flat-colors-suite-14.04.1/temp/build.log'

 * Messages for package x11-themes/ambiance-radiance-flat-colors-suite-14.04.1:

 * Fetch failed for 'x11-themes/ambiance-radiance-flat-colors-suite-14.04.1', Log file:
 *  '/var/tmp/portage/x11-themes/ambiance-radiance-flat-colors-suite-14.04.1/temp/build.log'

**Comment by jorgicio** [comment]
Hi! Thanks for the issue. I just added the pkg_nofetch in both packages containing ambiance-radiance. Please, try again.
