### ISSUE TITLE
media-video/openshot hash is wrong

### ISSUE THREAD

**Issue by weedy** [jorgicio/jorgicio-gentoo#140]
!!! Fetched file: openshot-qt-2.4.2.tar.gz VERIFY FAILED!
!!! Reason: Failed on BLAKE2B verification
!!! Got:      4b02d9ebe33b3cce190909fa5df8ac476be85efa96acdbd64e37cdbf3d663943cb83ba6699ff87b479ab382d00e8ee03cd27560894271ab0bcf0b811b694199e
!!! Expected: 403c612c2f6560dfdea8a5380f534ffb3ee775e7473fc72aa75dadcb9794deeadd2d55b0acd36d0a9fa6972c7e00250f095f4c4b934ffdc98dbc36d46fac8e3e

So it cannot be installed. (or my internet is shit...)

**Comment by jorgicio** [comment]
Probably your internet is shit, because I tried here with a decent connection, and passes all tests without problems. Try downloading again.

**Comment by weedy** [comment]
wtf, i can use curl to get the archive. But if I let emerge pull it down it bails out every time.
