### ISSUE TITLE
Unavailable repository 'seeds'

### ISSUE THREAD

**Issue by fturco** [jorgicio/jorgicio-gentoo#144]
When updating repositories with `emaint sync -a` I get the following warning message:

```
=== Sync completed for jorgicio
q: Updating ebuild cache for /var/db/repos/jorgicio ... 
q: Finished 402 entries in 0.003915 seconds
Unavailable repository 'seeds' referenced by masters entry in '/var/db/repos/jorgicio/metadata/layout.conf'
```

Contents of `/var/db/repos/jorgicio/metadata/layout.conf`:

```
repo-name = jorgicio
masters = seeds gentoo
profile-formats = portage-1
```

Is the `seeds` repository required if you want to use the `jorgicio` repository? I only need the latter one on my system...

**Comment by jorgicio** [comment]
By the moment, yes, the seeds repository is needed because some of the packages I maintain (vala-panel and vala-panel-appmenu) need ewmh, which is present in the seeds overlay.
If you find this is annoying, I'll replicate the ewmh ebuilds here, so I won't need another repo anymore.

**Comment by simonvanderveldt** [comment]
I'm seeing this as well (as expected). Would be nice if the ebuilds could be copied here (even though I personally don't have a need for the vala packages) to get rid of the message.

**Comment by jorgicio** [comment]
You're welcome. Additionally, I found the original ebuilds are using an old EAPI, so I moved them to the 6 version. (I don't know if EAPI=7 is working well with distutils-r1.eclass)
