### ISSUE TITLE
dev-libs/box2d-9999 does not compile

### ISSUE THREAD

**Issue by m4rkusxxl** [jorgicio/jorgicio-gentoo#150]
* Consider not inheriting the cmake eclass.
 * ERROR: dev-libs/box2d-9999::jorgicio failed (configure phase):
 *   FATAL: Unable to find CMakeLists.txt

It seems to use prelink5.

**Comment by jorgicio** [comment]
I noted the build method changed, so I'll try to understand how does it build and fix it.

**Comment by jorgicio** [comment]
I noticed that, despite of the usage of the premake, it can't find an install method, so I masked the 9999 version. Also, reworked the box2d entirely and it builds and installs fine.

You should try the 2.3.x versions instead.
