### ISSUE TITLE
x11-themes/faba-icon-theme bump to 4.3

### ISSUE THREAD

**Issue by simonvanderveldt** [jorgicio/jorgicio-gentoo#155]
A new release (4.3) has been made for the faba icon theme, see https://github.com/snwh/faba-icon-theme/releases
It seems like the build system has been changed to meson, so might be a bit more work than a regular bump. If you need some help just let me know.

P.S. The update to meson also means the 9999 is probably no longer working (I haven't tried that though).

**Comment by jorgicio** [comment]
Thanks for the reports. Sorry for being late, I wasn't home.

Now it's all bumped.

**Comment by simonvanderveldt** [comment]
No problem, thanks for the updates! :)
