### ISSUE TITLE
app-editors/visual-studio-code-1.33.0 - missing LICENSE file

### ISSUE THREAD

**Issue by yuri1969** [jorgicio/jorgicio-gentoo#165]
Hello,
for some strange reason, in 1.33.0 release the LICENSE file got converted to RTF format.
So instead of a plain text `resources/app/LICENSE.txt` you now have `resources/app/LICENSE.rtf`.

The ebuild needs to reflect that. I could make a PR but don't know how to handle the binary RTF situation.

**Comment by jorgicio** [comment]
Hi! I just had to rename the ".txt" for ".rtf" extension and done.

Thank you!
