### ISSUE TITLE
media-libs/freeimage libs - missing the most of the symbols

### ISSUE THREAD

**Issue by vpelcak** [jorgicio/jorgicio-gentoo#169]
Version 3.18 from your repo:

triarius ~ # nm -D /usr/lib/libfreeimage.so
                 w __cxa_finalize
                 w __gmon_start__
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
triarius ~ # nm -D /usr/lib/libfreeimageplus.so
                 w __cxa_finalize
                 w __gmon_start__
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable

After downgrade to 3.14:
nm -D /usr/lib/libfreeimage.so | wc -l
1113

**Comment by jorgicio** [comment]
Sorry, I don't maintain that package, you could report that issue in the [Gentoo's Bugzilla](https://bugs.gentoo.org)

If you have any question, feel free to reopen this issue.

**Comment by vpelcak** [comment]
Hello.

You are not maintaining packages in our overlay?
FreeImage from  Gentoo repos is working well, the one from your repo is broken.

**Comment by jorgicio** [comment]
Of course I maintain packages in my overlay, but not that package you're requesting. Indeed, it's not on my overlay. Once I did it, but after I saw it on the official Gentoo Tree, I stopped maintaining it.

**Comment by vpelcak** [comment]
OK. Thank you for the info.
