### ISSUE TITLE
mail-client/aerc should have a dependency on dev-python/colorama

### ISSUE THREAD

**Issue by MrZammler** [jorgicio/jorgicio-gentoo#171]
Hi!

Just installed aerc on my system, but when viewing a mail results in an error that colorama is missing. Installing dev-python/colorama fixes it, so could you add it as a dependency ?

Thanks!

**Comment by MrZammler** [comment]
I also get this error on a mail (not sure of package or an aerc error though):

/usr/share/aerc/filters/html: line 5: exec: socksify: not found

**Comment by jorgicio** [comment]
Hi, there are two dependencies missing: colorama and dante (which provides the socksify binary). I'll add them then.
Thanks.
