### ISSUE TITLE
net-im/whatsapp-for-desktop: fail to launch

### ISSUE THREAD

**Issue by tharvik** [jorgicio/jorgicio-gentoo#18]
After emerging net-im/whatsapp-for-desktop, I tried to launch it but it fail because of missing libgconf. Adding gnome-base/gconf in RDEPEND fix the issue.

```
/opt/WhatsAppForDesktop/UnofficialWhatsApp: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

**Comment by jorgicio** [comment]
Fixed. Thanks for reporting!
