### ISSUE TITLE
net-im/telegram-bin has an "update" button in the GUI even without the "updater" USE flag

### ISSUE THREAD

**Issue by Pastafarianist** [jorgicio/jorgicio-gentoo#20]
The title says it all. Here's what I have installed:

    $ eix telegram-bin
    [I] net-im/telegram-bin [1]
         Available versions:  (~)0.8.38^m {updater}
         Installed versions:  0.8.38^m(19:55:17 28/07/15)(-updater)
         Homepage:            https://tdesktop.com/
         Description:         Telegram Desktop Messenger (official client) binary version
    
    [1] "jorgicio" /var/lib/layman/jorgicio

And here's a screenshot of the GUI:

![image](https://cloud.githubusercontent.com/assets/1315874/9246131/1f601cc0-41b2-11e5-9f25-e971e5f965a8.png)

**Comment by jorgicio** [comment]
Mmmmm... Try refreshing the overlay and try again :)

**Comment by Pastafarianist** [comment]
Works now, thanks!

**Comment by Pastafarianist** [comment]
Unfortunately I have to reopen this, the issue shows up again in 0.8.52.

**Comment by jorgicio** [comment]
Well 0.8.55 is the most recent stable and it's on this overlay. Sync again and tell me what's going on.

**Comment by Pastafarianist** [comment]
It's gone, but maybe because that's the latest official version? :)

**Comment by jorgicio** [comment]
Surely I don't know; also, I modified some things to get rid this issue. Here it doesn't happen, at least.
I suggest to resync this overlay, more frequently.
