### ISSUE TITLE
Adding proper keywords for arc-theme?

### ISSUE THREAD

**Issue by acrox999** [jorgicio/jorgicio-gentoo#21]
It seems that arc-themes, faba and moka ebuilds did not have any keywords defined, and perhaps it might be better to define them so that users wouldn't have to do any keyword changes to their system?

**Comment by jorgicio** [comment]
Well, those packages are in constant upgrading because repos do so. Because of that, those packages are without KEYWORDS defined, as don't have defined versions of that. I also don't know when those repos have major upgrades.

**Comment by acrox999** [comment]
Ah, yes. You're right, I just realised that.

Well, not much of an issue here then.
