### ISSUE TITLE
Eclipse theme is broken after upgrading to 4.5.0

### ISSUE THREAD

**Issue by Pastafarianist** [jorgicio/jorgicio-gentoo#24]
Hi. I don't know if this is your issue or the upstream's but it looks like starting with version 4.5.0, Eclipse disregards system theme and just uses the first thing available. I guess that's Swing or GTK, but I'm not sure. It looks horrible under KDE.

![image](https://cloud.githubusercontent.com/assets/1315874/9693369/8a5303be-5358-11e5-9cea-cdfdd3106bc3.png)

Could you look into this issue?

**Comment by jorgicio** [comment]
Well... as I know, it's not a packaging issue, but  the Eclipse itself issue.
The same happened since Luna, and may be, you can find the answer there:
https://github.com/guari/eclipse-ui-theme/issues/73

Hope it helps.

**Comment by Pastafarianist** [comment]
Thanks for the link.
