### ISSUE TITLE
media-sound/lollypop-0.9.42::jorgicio  PYTHON_TARGETS="python3_4 -python3_3" no Settings schema is installed

### ISSUE THREAD

**Issue by Bratzmeister** [jorgicio/jorgicio-gentoo#25]
After installing lollypop-0.9.42 I tried to start it and get the following error:

`(lollypop:11541): GLib-GIO-ERROR **: Settings schema 'org.gnome.Lollypop' is not installed`

**Comment by jorgicio** [comment]
Well... as I noticed (once happened to me), it's a Lollypop issue itself. Check this https://github.com/gnumdk/lollypop/issues/59 and tell me if helped.

**Comment by Bratzmeister** [comment]
Hey, I have stumbled upon this before and tried what they advise. On my system there is no /usr/local/share folder. The guy behind your link had the Schema-file in this folder. So I can't reproduce what they advise.

**Comment by jorgicio** [comment]
That's weird as I added --disable-schemas in the ebuild.
Try now with /usr/share instead of /usr/local/share.
Or try a clean install of Lollypop just in case. I also found this: https://github.com/gnumdk/lollypop/issues/204

**Comment by Bratzmeister** [comment]
Clean install didn't help, but running `glib-compile-schemas /usr/share/glib-2.0/schemas/` afterwards did.

**Comment by jorgicio** [comment]
Oh, well. Thanks for the adversitement, I hope can find a fix for that to put it in the ebuild.

**Comment by Bratzmeister** [comment]
Anytime! Thanks for providing this ebuild!

**Comment by Bratzmeister** [comment]
Guess It is still worth the attention, since I got asked twice about this issue already. Maybe people will find the fix easier now.

**Comment by jorgicio** [comment]
Well, I found what happened. I found I must add this:

pkg_preinst(){
	gnome2_schemas_savelist
}

This fixed the issue. Sorry for the inconveniences.
Tried here and working.
