### ISSUE TITLE
New version Popcorn Time

### ISSUE THREAD

**Issue by talesam** [jorgicio/jorgicio-gentoo#3]
I've tested both versions, but the version of this site (https://popcorntime.io/) is better. and has a newer version. You could update !!

Update popcorntime-bin-3.2.ebuild

**Comment by mcder3** [comment]
No se si sera posible que puedas actualizar el ebuild para la nueva versión de popcorn-time (https://popcorntime.sh/)

**Comment by jorgicio** [comment]
I don't maintain this ebuild anymore, so I'll close this.
