### ISSUE TITLE
[lollypop] Missing dependency on dev-lang/python[sqlite]

### ISSUE THREAD

**Issue by simonvanderveldt** [jorgicio/jorgicio-gentoo#30]
First of all thanks for the overlay!
I just installed lollypop and when I wanted to start it it gave the following error:
```
simon@simon-desktop ~/dev/simonvanderveldt $ lollypop 
No module named 'requests'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 25, in <module>
    from lollypop.application import Application
  File "/usr/lib64/python3.4/site-packages/lollypop/application.py", line 39, in <module>
    from lollypop.database import Database
  File "/usr/lib64/python3.4/site-packages/lollypop/database.py", line 13, in <module>
    import sqlite3
ImportError: No module named 'sqlite3'
```

So it seems we're missing a dependency on the `sqlite` USE flag for python3.

Also note the `No module named 'requests'`, since Lollypop still starts without it but can't pull in data from Wikipedia for example maybe it should be a dependency behind a USE flag?

**Comment by jorgicio** [comment]
Hi! Thanks for the notice.
About sqlite, is already added as a mandatory dependence in Python. And fixed the issue, is with python-wikipedia package.
Try resync and reinstall both lollypop and python-wikipedia. For the latter, do it with the --oneshot option.

Thanks again!

**Comment by simonvanderveldt** [comment]
@jorgicio Thanks for the quick response!
Just updated and the sqlite USE dependency isn't picked up. Reading the docs it seems to be caused by the fact that `PYTHON_REQ_USE` should be set before `inherit python-r1`
https://wiki.gentoo.org/wiki/Project:Python/python-r1#PYTHON_REQ_USE

Regarding `No module named 'requests'`, I think my wording was a bit vague.
What I meant is that `requests`apparently is an optional dependency and as such Lollypop could depend on it when for example the USE flag `requests` is set.

**Comment by jorgicio** [comment]
Alright, fixed!

Also, requests is a dependency for python-wikipedia, which is a dependency for Lollypop. Try reinstalling both packages with the --oneshot option :D

**Comment by simonvanderveldt** [comment]
LGTM
```
equery g lollypop-0.9.62
 * Searching for lollypop0.9.62 ...

 * dependency graph for media-sound/lollypop-0.9.62
 `--  media-sound/lollypop-0.9.62  amd64 
   `--  dev-lang/python-3.3.5-r1  (>=dev-lang/python-3.3.2-r2) amd64  [sqlite]
   `--  dev-lang/python-3.4.3  (dev-lang/python) amd64  [sqlite]
   `--  dev-lang/python-3.5.0-r1  (dev-lang/python) [~amd64 keyword]  [sqlite]
```
