### ISSUE TITLE
Telegram Desktop executable needs MPROTECT disabled to run on hardened systems with PaX.

### ISSUE THREAD

**Issue by TheReverend403** [jorgicio/jorgicio-gentoo#33]
See https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/firefox/firefox-42.0.ebuild#n290

**Comment by jorgicio** [comment]
Done. Resync and try again.

**Comment by TheReverend403** [comment]
Yep, all good. Sorry for the wait.
