### ISSUE TITLE
net-libs/nodejs fails to build on old gcc because of missing dependency

### ISSUE THREAD

**Issue by Gosha** [jorgicio/jorgicio-gentoo#38]
This was marked as stable, so I figured I'd emerge it to play around. However it failed to build on my machine with gcc-4.7 but worked as soon as I upgraded to gcc-4.9. So maybe adding a dependency for gcc-4.8 might be a good idea.

As a note, I had gcc-4.9 installed, but not chosen as the system default.

**Comment by jorgicio** [comment]
Hi! As a dependency, was not mentioned on variables such as DEPEND or RDEPEND, but that's mentioned on the pkg_pretend in the ebuild. Those lines are there:

pkg_pretend() {
	if [[ ${MERGE_TYPE} != "binary" ]] ; then
		if ! test-flag-CXX -std=c++11 ; then
			die "Your compiler doesn't support C++11. Use GCC 4.8, Clang 3.3 or newer."
		fi
	fi
}


It says what you mentioned, so with pretending is enough. Thanks!

PS: btw, why the heck on these days some people is using older GCC versions when unsupported? xD

**Comment by Gosha** [comment]
Oh so I should've run a --pretend first?

Well, 4.7 hadn't caused any errors yet, and apparently I missed the memo : P
