### ISSUE TITLE
dropbox needs RDEPEND on ncurses:5/5

### ISSUE THREAD

**Issue by karolherbst** [jorgicio/jorgicio-gentoo#39]
I got an preserved-rebuild entry for it:

>>> package: sys-libs/ncurses-6.0-r1
 *  - /lib64/libncurses.so.5
 *  - /lib64/libncurses.so.5.9
 *      used by /opt/dropbox/_curses.so (net-misc/dropbox-3.14.5)

I think it should RDEPEND on || ( ncurses:0/5 ncurses:5/5 ).

**Comment by jorgicio** [comment]
As I noticed, Dropbox uses its own curses implementation. Even in the official Gentoo repos, it does not need ncurses as a dependency. I think more information is needed, because it does not happen here.

**Comment by karolherbst** [comment]
well on my system dropbox doesn't install any ncurses libraries. And this preserved-rebuild entry happened on my system after a ncurses upgrade from 5.9 to 6.0. I don't think portage detects it if dropbox gets first installed when only ncurses 6.0 is installed

**Comment by jorgicio** [comment]
ncurses is currently slotted, so check first what did you installed. If using unstable branch, it depends on which did you installed as required as a dependency. Try removing ncurses (both slots) and then do a emerge @world to install it itself if required.

**Comment by karolherbst** [comment]
removing both ncurses:0 and ncurses:5 and doing a @world update after it just installs ncurses-6.0-r1.

this leave me with this preserved-rebuild entry:

```
>>> package: sys-libs/ncurses-5.9-r101
 *  - /usr/lib32/libncurses.so.5
 *      used by /opt/dropbox/_curses.so (net-misc/dropbox-3.14.5)
```

one way or another, /opt/dropbox/_curses.so  links against libncurses.so.5, so this binary has to be provided by something and this is all ncurses:*/5 packages for now (and none of the ncurses:*/6 ones)

**Comment by jorgicio** [comment]
As I noticed, that problem happened in previous versions of Dropbox (until 3.12, which was fixed). But I noticed that it happens again, so you're right. Fixed.

Thanks.
