### ISSUE TITLE
dropbox start failes with qt5 error

### ISSUE THREAD

**Issue by flower1024** [jorgicio/jorgicio-gentoo#42]
if i start dropbox it complains about an permission error. but it points to an error file with additonal info. this seems to be the real error (i attached the complete file):

Traceback (most recent call last):
  File "dropbox/client/main.py", line 4698, in main_startup
  File "dropbox/client/main.py", line 2043, in run
  File "ui/common/uikit.py", line 401, in create_ui_kit
  File "dropbox/client/ui/qt/**init**.py", line 13, in <module>
  File "PyQt5/QtCore.py", line 14, in <module>
ImportError: /opt/dropbox/PyQt5.QtCore.so: undefined symbol: _ZN19QItemSelectionModel8setModelEP18QAbstractItemModel
[dropbox_errorjFvr5M.txt](https://github.com/jorgicio/jorgicio-gentoo/files/131753/dropbox_errorjFvr5M.txt)

please ask if you need any additional infos; not sure what i need to provide.

**Comment by jorgicio** [comment]
Mmmm...check about your qt5 packages installation. Maybe you must recompile them again. Here works flawlessly.

**Comment by flower1024** [comment]
ok, i did rebuild qt5core. the error did not change.
whats your qt5 version?

[ebuild   R    ] dev-qt/qtcore-5.4.2:5::gentoo  USE="icu systemd -debug {-test}" 0 KiB

**Comment by jorgicio** [comment]
I'm using 5.5.1. However, There are more QT5-related packages implied in Dropbox. Did you rebuild them too?

**Comment by flower1024** [comment]
not yet; i try

**Comment by flower1024** [comment]
i have recompiled this packages (found them in your dropbox.ebuild); however it did not change anything

[ebuild   R    ] dev-libs/glib-2.44.1-r1:2::gentoo  USE="dbus (mime) xattr -debug (-fam) (-selinux) -static-libs -systemtap {-test} -utils" ABI_X86="(64) -32 (-x32)" PYTHON_TARGETS="python2_7" 0 KiB
[ebuild   R    ] dev-qt/qtnetwork-5.4.2:5::gentoo  USE="ssl -bindist -connman -debug -networkmanager {-test}" 0 KiB
[ebuild   R    ] dev-qt/qtdbus-5.4.2:5::gentoo  USE="-debug {-test}" 0 KiB
[ebuild   R    ] dev-qt/qtgui-5.4.2-r1:5::gentoo  USE="dbus gif gtkstyle harfbuzz jpeg png udev xcb -accessibility -debug -egl -eglfs -evdev -gles2 -ibus {-test}" 0 KiB
[ebuild   R    ] dev-qt/qtwidgets-5.4.2:5::gentoo  USE="gtkstyle png xcb -debug -gles2 {-test}" 0 KiB
[ebuild   R    ] dev-qt/qtprintsupport-5.4.2:5::gentoo  USE="-cups -debug -gles2 {-test}" 0 KiB
[ebuild   R    ] dev-qt/qtquick1-5.4.2:5::gentoo  USE="opengl xml -debug -designer {-test} -webkit" 0 KiB
[ebuild   R    ] dev-qt/qtwebkit-5.4.2:5::gentoo  USE="gstreamer opengl udev webp -debug -gstreamer010 -multimedia -printsupport -qml {-test}" 0 KiB

**Comment by flower1024** [comment]
a downgrade to dropbox-3.12.6 works

**Comment by jorgicio** [comment]
Maybe this was why I left it as stable. You can also try uninstalling dropbox and install 3.14.5 again. If still failing, you can go to 3.12.6.

**Comment by flower1024** [comment]
an unmerge and new emerge of the unstable version did not change anything.
however when i installed this gentoo box i did not notice that dropbox was marked stable.... so i just removed it from my accept_keywords now

for me its fine now - do you want me to close this issue or should i left it open if you have further questions regarding the unstable version?

**Comment by jorgicio** [comment]
Leave it open, please. It may work to people to report it if having the same problems as you. Thanks.

**Comment by flower1024** [comment]
thank you for your time ;-)

**Comment by flower1024** [comment]
Hi,
you have unmasked the new dropbox ebuild but i still have the same problem.
i have masked it for now and downgraded to net-misc/dropbox-3.12.6::jorgicio which works fine

**Comment by jorgicio** [comment]
Ok, I don't know why is this happening to you on if it happens to somebody else. Left latest version as unstable again.
