### ISSUE TITLE
Problem megasync-2.7.2 

### ISSUE THREAD

**Issue by Brutico** [jorgicio/jorgicio-gentoo#45]
Hi, It seems that the link ... you can not fix it? Thank you

```
cat /tmp/portage/net-misc/megasync-2.7.2/temp/build.log
>>> Downloading 'https://mega.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync_2.7.2_amd64.deb'
--2016-03-24 17:05:15--  https://mega.nz/linux/MEGAsync/xUbuntu_14.04/amd64/megasync_2.7.2_amd64.deb
Resolving mega.nz... 154.53.224.142, 154.53.224.150, 154.53.224.162, ...
Connecting to mega.nz|154.53.224.142|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-24 17:05:16 ERROR 404: Not Found.

!!! Couldn't download 'megasync_2.7.2_amd64.deb'. Aborting.
 * Fetch failed for 'net-misc/megasync-2.7.2', Log file:
 *  '/tmp/portage/net-misc/megasync-2.7.2/temp/build.log'
```

**Comment by jorgicio** [comment]
Hi! I noticed the app is opensource, so this is fixed and now you can compile it. Resync and try again.

**Comment by vasettoo** [comment]
Hi, Jorgicio! I am posting this here as it's the most recent post regarding megasync.
`# emerge -av nautilus-megasync

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] net-dns/c-ares-1.10.0-r1::gentoo  USE="-static-libs" ABI_X86="32 (64) (-x32)" 791 KiB
[ebuild  N     ] dev-libs/crypto++-5.6.2-r2::gentoo  USE="-static-libs" 1112 KiB
[ebuild  N     ] dev-libs/libuv-1.4.2:0/1::gentoo  USE="-static-libs" ABI_X86="32 (64) (-x32)" 995 KiB
[ebuild  N    #] net-misc/megasync-2.8.0::jorgicio  USE="ares cryptopp curl nautilus qt4 readline sqlite zlib -examples -freeimage -libsodium -qt5 -threads" 10402 KiB
[ebuild  N    #] gnome-extra/nautilus-megasync-2.8.0::jorgicio  47 KiB
[blocks B      ] gnome-extra/nautilus-megasync ("gnome-extra/nautilus-megasync" is hard blocking net-misc/megasync-2.8.0)

Total: 5 packages (5 new), Size of downloads: 13344 KiB
Conflict: 1 block (1 unsatisfied)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (gnome-extra/nautilus-megasync-2.8.0:0/0::jorgicio, ebuild scheduled for merge) pulled in by
    nautilus-megasync


For more information about Blocked Packages, please refer to the following
section of the Gentoo Linux x86 Handbook (architecture is irrelevant):

https://wiki.gentoo.org/wiki/Handbook:X86/Working/Portage#Blocked_packages
`
I've checked the ebuild but my knowledge is limited for solving this block.
I appreciate any help on this.
Best regards!

**Comment by jorgicio** [comment]
Hi! I forgot to mention:

megasync build also comes with the Nautilus extension if needed, so if you want to use it along with megasync, you have 2 ways:

1. Install megasync with USE="nautilus" enabled.
2. Install megasync with USE="nautilus" disabled and then, install nautilus-megasync.

Choose whatever you want and tell me what's going on, please.

**Comment by vasettoo** [comment]
I see, my problem will be solved by adding:

`USE=" -nautilus" emerge -av megasync`

Thank you for the hint.
Best ragards!

**Comment by jorgicio** [comment]
Best regards to you!

Just a warning: I'm planning to remove the nautilus-megasync package sometime in the future, but first, I need to know if compiling megasync with nautilus support is working fine. If anybody tries megasync with the USE="nautilus" enabled and tells me what's going on with that and everything is fine, I'll remove nautilus-megasync in the near future.

**Comment by vasettoo** [comment]
Hi, again! Emerging megasync  with the above workaround runs fine, but I can't start the program - not usable. When using nautilus USE flag I get compile error:

` * Running qmake ...
 *  - fixed CONFIG in MEGAUpdater/MEGAUpdater.pro
 *  - fixed CONFIG in MEGASync/mega/contrib/QtCreator/MEGASimplesync/MEGASimplesync.pro
 *  - fixed CONFIG in MEGASync/mega/contrib/QtCreator/MEGACli/MEGACli.pro
 *  - fixed CONFIG in MEGASync/MEGASync.pro
 *  - fixed CONFIG in MEGACrashAnalyzer/MEGACrashAnalyzer.pro
Cannot find file: with_ext.
 [ !! ]

 * Running qmake has failed! (see above for details)
 * This shouldn't happen - please send a bug report to https://bugs.gentoo.org/

 * ERROR: net-misc/megasync-2.8.0::jorgicio failed (configure phase):
 *   eqmake4 failed
 * 
 * Call stack:
 *     ebuild.sh, line  133:  Called src_configure
 *   environment, line 2994:  Called eqmake4 'MEGA.pro' 'CONFIG+=release' 'with_ext'
 *   environment, line 1631:  Called die
 * The specific snippet of code:
 *           die "eqmake4 failed";
 * 
 * If you need support, post the output of `emerge --info '=net-misc/megasync-2.8.0::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=net-misc/megasync-2.8.0::jorgicio'`.
 * The complete build log is located at '/tmp/portage/net-misc/megasync-2.8.0/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/net-misc/megasync-2.8.0/temp/environment'.
 * Working directory: '/tmp/portage/net-misc/megasync-2.8.0/work/MEGAsync-2_8_0_0_Linux/src'
 * S: '/tmp/portage/net-misc/megasync-2.8.0/work/MEGAsync-2_8_0_0_Linux' `

Complete build log: http://paste2.org/JfYsN5FX

**Comment by jorgicio** [comment]
Ok, I found the problem. Please resync, try again and tell me what's going on.

**Comment by vasettoo** [comment]
Nope, all the same error and if USE="-nautilus" - nothing happens as if there's no application, even the icon is not the red logo of MEGA. Below is the new build log:
[http://paste2.org/pk26D5et](url)

**Comment by jorgicio** [comment]
Ok, that's weird, but I found the problem. Resync and please try again.

**Comment by vasettoo** [comment]
At first all compiled successfully, but now I can't start the application - the icon is missing the red logo again and even starting it from terminal returns nothing. I am at a loss what to do...

**Comment by jorgicio** [comment]
Please, paste the output of equery f megasync.

**Comment by vasettoo** [comment]
http://paste2.org/pOV6Bmgj

**Comment by jorgicio** [comment]
Ok, fixed. My bad. Resync and try again. Also, if needed, restart the desktop as a suggestion.

**Comment by vasettoo** [comment]
Still nothing happens after resync and restarting gnome-shell 

> Alt+F2 > r > Enter

>

**Comment by jorgicio** [comment]
Mmmm... paste the output of `equery f megasync` again, please. And when "restarting the desktop", I meant logout and login.

**Comment by vasettoo** [comment]
Here you are:
http://paste2.org/hwXOnVbH

**Comment by vasettoo** [comment]
I fixed the icon by editing the path to mega.png in megasync.desktop, but the exec doesn't work as expected, even invoked from terminal.

**Comment by jorgicio** [comment]
Mmmm... that's weird, try running `megasync` from the Alt+F2.

**Comment by vasettoo** [comment]
Still nothing happens.

**Comment by jorgicio** [comment]
Mmmmm... if at running from command line gives an output, please paste it. Here works fine, but compiled without Nautilus support (I use MATE)

**Comment by vasettoo** [comment]
That's the real problem - no output is given when run from command line, only a new line appended as if megasync has exited.

**Comment by vasettoo** [comment]
Neither way's working - nautilus USE flag enabled or disabled.

**Comment by jorgicio** [comment]
Mmmm... Try deleting all configuration files if created (in home directory). I tried with qt4 and qt5 and working fine. Try compile with qt5 instead of qt4.

**Comment by vasettoo** [comment]
I suspected you'll say that and I'm waiting for qt5 to finish to compile. Weird thing is I have no configuration files/folder in my home directory created by megasync.

**Comment by vasettoo** [comment]
Still no luck and another error:
http://paste2.org/3N3aH3Zy

**Comment by jorgicio** [comment]
My bad, I missed a dependency. I'll check what's going on.

**Comment by jorgicio** [comment]
I found that, I hope it may help. http://askubuntu.com/questions/631445/mega-sync-client-freezes-hangs-turns-off-after-sleep-suspend

**Comment by vasettoo** [comment]
So, I switched to qt4, because qt5 gives the previously posted error on compile. When started, megasync creates its folder in ~/.local/share/data, but no process is shown as active in system monitor. Don't know what else to do.
Is it possible to restore megasync 2.7.2 as it was the last working version for me?
Thank you sincerely for your efforts on this topic!

**Comment by jorgicio** [comment]
Yeah, I explain:

The error given when you compiled with qt5 support is because there was a missing dependency: qtwidgets, which I already added today. About restoring the 2.7.2 version... although I can do this, I cannot through a deb version because when the deb maintainers delete all older versions when a new one was released. But I can restore the 2.7.2 version but as a source-based version, not binary one.

**Comment by vasettoo** [comment]
Some update: I fixed the error for qt5 - needed dependencies for 'qtconcurrent' and 'qtnetwork' which I hadn't installed prior emerge of megasync. Now the local folder of megasync is placed directly in ~/.local/share/ and created after starting the exec but still no process running active in system monitor. At least my folder for MEGA has its icon back. Still investigating the root of the problem - some additional options in the exec maybe needed? Probably my session is preventing the app from starting correctly...

**Comment by jorgicio** [comment]
Thanks for the warning, I added those dependencies to the list. I don't know what's the root of your problem, because here works fine. Comparing with the Debian-based one (tried with 2.8.0), the structure of the tree is the same as you have when running `equery f megasync`, and here tried both with qt4 and qt5 in MATE and working fine, so I think the problem must be somewhere else.

You can also debug the binary with gdb to watch is there something else.
And thanks again for the warnings.

**Comment by vasettoo** [comment]
Hi, jorgicio! Good news after nearly two months and a half. Today I have installed and run successfully version 2.9.5 of MEGASync. I think the root of my problem previously was the 'nss' with curl package which uses Mozilla's ssl option. Emerge complained about 'USE=curl_ssl_nss' when trying to install megasync 2.9.5 and after disabling it with 'USE=-curl_ssl_nss' and adding 'USE=curl_ssl_openssl' for curl and pycurl packages compilation ended successfully. I hope this helps others having this problem which bothered me for some time.
Once again a huge THANKS for your hard work and patience with solving my issues with this great software.
Best regards!

**Comment by jorgicio** [comment]
Hi! I though I fixed this bug, please tell me what's going on.

**Comment by jorgicio** [comment]
As there are no response and also the issue seems fixed in upstream, I'll close this.
