### ISSUE TITLE
media-sound/lollypop-0.9.112: Please change licence from "LGPL-3.0" to "LGPL-3"

### ISSUE THREAD

**Issue by hartwork** [jorgicio/jorgicio-gentoo#52]
Hi!

The license file is called "LGPL-3" in Gentoo, see `/usr/portage/licenses/LGPL-3`.
Without this fix, users need to act to
```
The following license changes are necessary to proceed:
 (see "package.license" in the portage(5) man page for more details)
# required by media-sound/lollypop (argument)
=media-sound/lollypop-0.9.112 LGPL-3.0
```
without real need to. Thanks in advance!

Best, Sebastian

**Comment by jorgicio** [comment]
Done. If you find some packages with the same issue, please report it.

Thanks.

Don't forget resync!

**Comment by hartwork** [comment]
Muchas gracias, saludos a chile! :smiley:
