### ISSUE TITLE
New versions available : atom-bin, visual-studio-code and megasync

### ISSUE THREAD

**Issue by LaurentTreguier** [jorgicio/jorgicio-gentoo#53]
Hello, the title here already says it all, a few packages have new versions available:
- atom-bin is now at version [1.9.9](https://github.com/atom/atom/releases/tag/v1.9.9)
- visual-studio-code is at version [1.4.0](https://code.visualstudio.com/updates)
- megasync is at version [2.9.8](https://github.com/meganz/MEGAsync/releases/tag/v2_9_8_0_Linux)

**Comment by jorgicio** [comment]
Done. Thanks for the report!
