### ISSUE TITLE
x11-misc/primus-20150328-r1 breaks optirun primus backend

### ISSUE THREAD

**Issue by mmirg** [jorgicio/jorgicio-gentoo#54]
Updating to your newest primus ebuild prevents optirun from being able to find the primus backend.

> optirun -b primus glxspheres
> [  278.429714] [ERROR]Accel/display bridge primus is not installed.

`primusrun`, which did not work with 20150328 due to being unable to find libGL.so.1 works again with 20150328-r1 but seems to use the Intel GPU instead of the Nvidia GPU (and provides similar performance to using the Intel GPU directly).  This issues seems to be similar to what I experience:  https://github.com/amonakov/primus/issues/101.  I've rolled back now to 20150328 and am able to use optirun with the primus backend again.

**Comment by jorgicio** [comment]
Hi!
By default, primus crashes with some versions of nvidia-drivers. I'll deleted the "workaround" and restore the original version again.

Resync, please.

Thanks!
