### ISSUE TITLE
libsodium needed for v.2.9.8

### ISSUE THREAD

**Issue by sedimentation-fault** [jorgicio/jorgicio-gentoo#56]
It has been some time since I was able to compile the **megasync 2.9.8** ebuild successfully, so I don't have any build logs or similar. But I do remember that compilation broke at some point due to not having libsodium. I put a '+' in front of 'libsodium' on this line:

`IUSE="+cryptopp +sqlite +libsodium +zlib +curl freeimage readline examples threads qt5 nautilus"`

in the ebuild - and all went well. Please consider this change for your ebuild too.
As far as I am concerned, this has resolved the issue for me, so you can mark this as solved.

**Comment by jorgicio** [comment]
Done. I force the libsodium support removing that flag and add the "--with-sodium" line.

Thanks. Resync and try again.
