### ISSUE TITLE
dev-qt/qmltermwidget: can not download tarball

### ISSUE THREAD

**Issue by OwenChia** [jorgicio/jorgicio-gentoo#57]
The problem is [here](https://github.com/jorgicio/jorgicio-gentoo/blob/master/dev-qt/qmltermwidget/qmltermwidget-0.1.0.ebuild#L17):
```
SRC_URI="${HOMEPAGE}/archive/v${PV} -> ${P}.tar.gz"
```
It should be:
```
SRC_URI="${HOMEPAGE}/archive/v${PV}.tar.gz -> ${P}.tar.gz"
```

**Comment by jorgicio** [comment]
Thanks. Fixed.
