### ISSUE TITLE
app-editors/atom-bin-1.10.2.ebuild: Build fails

### ISSUE THREAD

**Issue by l-x** [jorgicio/jorgicio-gentoo#61]
app-editors/atom-bin-1.10.2 build fails due to removed node executable

in `src_prepare()` the node executable is removed, in `src_install()` `fperms +x` is applied to it.

**Comment by jorgicio** [comment]
Done. My bad.
Thanks, it's now fixed. Resync and try again.

**Comment by l-x** [comment]
Wow, that was lightning fast! Thanks alot!
