### ISSUE TITLE
Atom doesn't work correctly with nodejs versions more than 4.x

### ISSUE THREAD

**Issue by gentoid** [jorgicio/jorgicio-gentoo#63]
I think, it requires a restriction like `<net-libs/nodejs-5`. Thanks

**Comment by jorgicio** [comment]
Done. That's weird because some other distros support Atom with nodejs 5. Anyways, fixed. Just sync and try again.

**Comment by OwenChia** [comment]
`<net-libs/nodejs-5` is not a good idea, what if I want to use the latest version?

**Comment by gentoid** [comment]
Thanks @jorgicio . Yeah, agree, it's weird, but it's a fact - atom's packages subsystem doesn't work with nodejs >= 5. Is it only on my machine? I don't know, actually. I tried to install nodejs 5.x and 6.x - had same effect

@OwenChia there's [nvm](https://github.com/creationix/nvm), but, probably, it might not fit your needs though

**Comment by gentoid** [comment]
Ok, I've installed `app-editors/atom` from main Gentoo repo, and it does work with latest NodeJS. So probably `atom-bin` is bundled with nodejs-4.x, and thus it conflicts with newer versions
