### ISSUE TITLE
Missing file for app-editors/atom-1.11.2 (lintian file)

### ISSUE THREAD

**Issue by vincepoencet** [jorgicio/jorgicio-gentoo#69]
Hello, 

The file atom-1.11.2-lintian is missing.

Here is my log:
* Messages for package app-editors/atom-bin-1.11.2:

 * ERROR: app-editors/atom-bin-1.11.2::jorgicio failed (install phase):
 *   !!! newins: /var/lib/layman/jorgicio/app-editors/atom-bin/files/atom-1.11.2-lintian does not exist

Thank you

**Comment by jorgicio** [comment]
Fixed. Uploaded the lintian file. Thanks!
