### ISSUE TITLE
x11-misc/caffeine gone again :-(

### ISSUE THREAD

**Issue by olifre** [jorgicio/jorgicio-gentoo#70]
I found this package just about today in this overlay and was really happy - I have already actively used in on openSUSE on several occasions, especially when doing presentations, sharing the screen etc. 

It also compiled fine and executed well, but I see now it's gone again... :cry: 
Do you know of another repository where it is maintained? Or is there something wrong with it? Or was it deleted just by accident?

**Comment by jorgicio** [comment]
Hi, sorry, I was using the one from the seeds overlay, but the maintainer already upgraded that version, so I didn't need my version anymore. If you want to install it, add the seeds overlay and install it.

Best regards!

**Comment by olifre** [comment]
> I was using the one from the seeds overlay

Thanks a lot for this hint! There's also other useful stuff in this overlay, so I'll just add it :+1:
