### ISSUE TITLE
>=media-sound/lollypop-0.9.219 fails to install with sandbox error

### ISSUE THREAD

**Issue by mmirg** [jorgicio/jorgicio-gentoo#71]
lollypop-0.9.220 and lollypop-0.9.219 fail to install with a sandbox error on my system.

` * ACCESS DENIED:  fchmodat:     /usr/share/lollypop/lollypop-sp
chmod: changing permissions of ‘/usr/share/lollypop/lollypop-sp’: Permission denied
`
```
* Final size of build directory: 5756 KiB
 * Final size of installed tree: 4516 KiB

 * --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 * LOG FILE: "/var/log/sandbox/sandbox-587.log"
 * 
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: fchmodat
S: deny
P: /usr/share/lollypop/lollypop-sp
A: /usr/share/lollypop/lollypop-sp
R: /usr/share/lollypop/lollypop-sp
C: chmod +x /usr/share/lollypop/lollypop-sp 
 * --------------------------------------------------------------------------------
```

**Comment by jorgicio** [comment]
Tried here and working with lollypop 0.9.221 (on the overlay). Maybe this was fixed in upstream. Please, resync and try again. Also, I added some things to the ebuild, such as the functions src_compile and src_install with the DESTDIR variable.

**Comment by mmirg** [comment]
Strange, I'm getting the same error with 0.9.221.  I wonder if there's something else wrong with sandbox and/or something else on my system.

**Comment by jorgicio** [comment]
That's strange. Please attach your `build.log` and your `emerge --info` and also tell me what sandbox version you have installed.

**Comment by mmirg** [comment]
`sys-apps/sandbox-2.10-r2`
[build.log.txt](https://github.com/jorgicio/jorgicio-gentoo/files/618518/build.log.txt)
[emerge.info.txt](https://github.com/jorgicio/jorgicio-gentoo/files/618520/emerge.info.txt)

**Comment by jorgicio** [comment]
I noticed you're using Funtoo. Anyways, as I see, the problem may be the sandbox version or the modifications Funtoo developers did to the ebuild. Try downgrading your sandbox version.

**Comment by mmirg** [comment]
Uninstalling and re-installing Lollypop seemed to do the trick, as I expected.  I'll see if I run into the issue again on the next upgrade and if it's a sandbox error then report it upstream to Funtoo.  Thanks.
