### ISSUE TITLE
media-sound/zita-at1-0.4.0::jorgicio doesn't build

### ISSUE THREAD

**Issue by rugubara** [jorgicio/jorgicio-gentoo#72]
>>> Emerging (4 of 4) media-sound/zita-at1-0.4.0::jorgicio
 * zita-at1-0.4.0.tar.bz2 SHA256 SHA512 WHIRLPOOL size ;-) ...           [ ok ]
>>> Unpacking source...
>>> Unpacking zita-at1-0.4.0.tar.bz2 to /var/tmp/portage/media-sound/zita-at1-0.4.0/work
>>> Source unpacked in /var/tmp/portage/media-sound/zita-at1-0.4.0/work
>>> Preparing source in /var/tmp/portage/media-sound/zita-at1-0.4.0/work/zita-at1-0.4.0/source ...
 * Applying zita-at1-0.4.0-Makefile.patch ...

 * Failed Patch: zita-at1-0.4.0-Makefile.patch !
 *  ( /var/lib/layman/jorgicio/media-sound/zita-at1/files/zita-at1-0.4.0-Makefile.patch )
 * 
 * Include in your bugreport the contents of:
 * 
 *   /var/tmp/portage/media-sound/zita-at1-0.4.0/temp/zita-at1-0.4.0-Makefile.patch.out

[zita-at1-0.4.0-Makefile.patch.out.gz](https://github.com/jorgicio/jorgicio-gentoo/files/654060/zita-at1-0.4.0-Makefile.patch.out.gz)

**Comment by jorgicio** [comment]
Thanks for the report. Tested here and fixed. It should work for you.
Greetings!
