### ISSUE TITLE
app-admin/f3-6.0 fails to build

### ISSUE THREAD

**Issue by jonashrem** [jorgicio/jorgicio-gentoo#75]
Build fails with dodoc: README does not exist

Please remove the line 

**dodoc README** 

from the ebuild

[build.log.zip](https://github.com/jorgicio/jorgicio-gentoo/files/700958/build.log.zip)
[f3-6.0-r1.ebuild.zip](https://github.com/jorgicio/jorgicio-gentoo/files/700957/f3-6.0-r1.ebuild.zip)

**Comment by jorgicio** [comment]
Hi!
I just noticed that f3 is in the official Portage tree, so I won't support it anymore.
Remove it, resync and reinstall it if you want it.

Thanks for the support ;)
