### ISSUE TITLE
net-im/corebird-1.4 failed to compile

### ISSUE THREAD

**Issue by Myu-Unix** [jorgicio/jorgicio-gentoo#78]
Hello there !

First, I would like to **thank you** for your overlay, I'm using it since quite some time now and I really appreciate it ! :)

I usually track the latest version of corebird from your overlay and today, I've tried to emerge corebird-1.4 from corebird-1.3.3 but it fails, it seems it needs vala 0.34 (as well as a `valac` binary) but those aren't merged automatically.

```
checking for valac... (cached) /usr/bin/valac-0.32
checking whether /usr/bin/valac-0.32 is at least version 0.34.0... no
configure: WARNING: no proper vala compiler found
configure: WARNING: you will not be able to compile vala source files
```

and then shortly after

`make[2]: valac: Command not found`

I'm using vala 0.32.1 right now.

Should this help, the full emerge log is below :

```

 emerge --ask =corebird-1.4

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U ~] net-im/corebird-1.4 [1.3.3] USE="spell%*" 

Would you like to merge these packages? [Yes/No] Yes

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) net-im/corebird-1.4::jorgicio
 * corebird-1.4.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...              [ ok ]
>>> Unpacking source...
>>> Unpacking corebird-1.4.tar.gz to /var/tmp/portage/net-im/corebird-1.4/work
>>> Source unpacked in /var/tmp/portage/net-im/corebird-1.4/work
>>> Preparing source in /var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4 ...
 * Running eautoreconf in '/var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4' ...
 * Running autopoint --force ...                                         [ ok ]
 * Running libtoolize --install --copy --force --automake ...            [ ok ]
 * Running aclocal -I m4 ...                                             [ ok ]
 * Running autoconf --force ...                                          [ ok ]
 * Running autoheader ...                                                [ ok ]
 * Running automake --add-missing --copy --foreign --force-missing ...   [ ok ]
 * Running elibtoolize in: corebird-1.4/
 * Running elibtoolize in: corebird-1.4/build-aux/
 *   Applying portage/1.2.0 patch ...
 *   Applying sed/1.5.6 patch ...
 *   Applying as-needed/2.4.3 patch ...
 * Disabling deprecation warnings ...                                    [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4 ...
 * econf: updating corebird-1.4/build-aux/config.guess with /usr/share/gnuconfig/config.guess
 * econf: updating corebird-1.4/build-aux/config.sub with /usr/share/gnuconfig/config.sub
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/corebird-1.4 --htmldir=/usr/share/doc/corebird-1.4/html --libdir=/usr/lib64 --disable-maintainer-mode --disable-schemas-compile --disable-video
checking for a BSD-compatible install... /usr/lib/portage/python3.4/ebuild-helpers/xattr/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for x86_64-pc-linux-gnu-gcc... x86_64-pc-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-pc-linux-gnu-gcc accepts -g... yes
checking for x86_64-pc-linux-gnu-gcc option to accept ISO C89... none needed
checking whether x86_64-pc-linux-gnu-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of x86_64-pc-linux-gnu-gcc... none
checking for x86_64-pc-linux-gnu-gcc option to accept ISO C99... -std=gnu99
checking for x86_64-pc-linux-gnu-gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by x86_64-pc-linux-gnu-gcc -std=gnu99... /usr/x86_64-pc-linux-gnu/bin/ld
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/x86_64-pc-linux-gnu-nm -B
checking the name lister (/usr/bin/x86_64-pc-linux-gnu-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-linux-gnu/bin/ld option to reload object files... -r
checking for x86_64-pc-linux-gnu-objdump... x86_64-pc-linux-gnu-objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-pc-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-pc-linux-gnu-ar... x86_64-pc-linux-gnu-ar
checking for archiver @FILE support... @
checking for x86_64-pc-linux-gnu-strip... x86_64-pc-linux-gnu-strip
checking for x86_64-pc-linux-gnu-ranlib... x86_64-pc-linux-gnu-ranlib
checking command to parse /usr/bin/x86_64-pc-linux-gnu-nm -B output from x86_64-pc-linux-gnu-gcc -std=gnu99 object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for x86_64-pc-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... x86_64-pc-linux-gnu-gcc -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-pc-linux-gnu-gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for x86_64-pc-linux-gnu-gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if x86_64-pc-linux-gnu-gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if x86_64-pc-linux-gnu-gcc -std=gnu99 static flag -static works... yes
checking if x86_64-pc-linux-gnu-gcc -std=gnu99 supports -c -o file.o... yes
checking if x86_64-pc-linux-gnu-gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the x86_64-pc-linux-gnu-gcc -std=gnu99 linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for valac... /usr/bin/valac-0.32
checking whether /usr/bin/valac-0.32 is at least version 0.28.0... yes
checking for x86_64-pc-linux-gnu-pkg-config... /usr/bin/x86_64-pc-linux-gnu-pkg-config
checking pkg-config is at least version 0.16... yes
checking for CB... yes
checking for valac... (cached) /usr/bin/valac-0.32
checking whether /usr/bin/valac-0.32 is at least version 0.34.0... no
configure: WARNING: no proper vala compiler found
configure: WARNING: you will not be able to compile vala source files
checking for glib-compile-resources... /usr/bin/glib-compile-resources
checking for xmllint... /usr/bin/xmllint
checking GStreamer 1.0 element gtksink >= 1.0... found
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/gmsgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by x86_64-pc-linux-gnu-gcc -std=gnu99... /usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating data/Makefile
config.status: creating data/hicolor/Makefile
config.status: creating data/hicolor/256x256/Makefile
config.status: creating data/hicolor/128x128/Makefile
config.status: creating data/hicolor/96x96/Makefile
config.status: creating data/hicolor/64x64/Makefile
config.status: creating data/hicolor/48x48/Makefile
config.status: creating data/hicolor/32x32/Makefile
config.status: creating data/hicolor/24x24/Makefile
config.status: creating data/hicolor/16x16/Makefile
config.status: creating po/Makefile.in
config.status: creating tests/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
./configure: line 17648: valac: command not found

                Corebird  1.4
                  Prefix: /usr
           Vala Compiler: valac    --pkg gtk+-3.0   --pkg json-glib-1.0   --pkg rest-0.7   --pkg sqlite3   --pkg libsoup-2.4   --pkg glib-2.0   --target-glib=2.38 -D SPELLCHECK --pkg gspell-1
           valac version: 
              C Compiler: x86_64-pc-linux-gnu-gcc -std=gnu99 -O2 -pipe
               Debugging: no
          Video disabled: yes
      Gst check disabled: no
  Spellchecking disabled: no

>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4 ...
make -j3 
make  all-recursive
make[1]: Entering directory '/var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4'
Making all in src
make[2]: Entering directory '/var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4/src'
make[2]: valac: Command not found
Makefile:1206: recipe for target 'libcorebird_la_vala.stamp' failed
make[2]: *** [libcorebird_la_vala.stamp] Error 127
make[2]: Leaving directory '/var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4/src'
Makefile:443: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4'
Makefile:375: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: net-im/corebird-1.4::jorgicio failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-im/corebird-1.4::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=net-im/corebird-1.4::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/net-im/corebird-1.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-im/corebird-1.4/temp/environment'.
 * Working directory: '/var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4'
 * S: '/var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4'

>>> Failed to emerge net-im/corebird-1.4, Log file:

>>>  '/var/tmp/portage/net-im/corebird-1.4/temp/build.log'

 * Messages for package net-im/corebird-1.4:

 * ERROR: net-im/corebird-1.4::jorgicio failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-im/corebird-1.4::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=net-im/corebird-1.4::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/net-im/corebird-1.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-im/corebird-1.4/temp/environment'.
 * Working directory: '/var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4'
 * S: '/var/tmp/portage/net-im/corebird-1.4/work/corebird-1.4'
```

Have a good day !

**Comment by jorgicio** [comment]
Hi! Thanks for your support at using my overlay.
I found the problem and fixed it. Resync and try again, please. (Current corebird version is 1.4.1, jic)

**Comment by Myu-Unix** [comment]
Hi and thanks for the update !

I tried again after a sync but it apparently still fails at finding the `valac` binary.

```
checking for valac... (cached) /usr/bin/valac-0.32
checking whether /usr/bin/valac-0.32 is at least version 0.34.0... no
configure: WARNING: no proper vala compiler found
configure: WARNING: you will not be able to compile vala source files
```

The full log is below

emerge --ask =corebird-1.4.1

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U ~] net-im/corebird-1.4.1 [1.3.3] USE="spell%*" 

Would you like to merge these packages? [Yes/No] Yes

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) net-im/corebird-1.4.1::jorgicio
 * corebird-1.4.1.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...            [ ok ]
>>> Unpacking source...
>>> Unpacking corebird-1.4.1.tar.gz to /var/tmp/portage/net-im/corebird-1.4.1/work
>>> Source unpacked in /var/tmp/portage/net-im/corebird-1.4.1/work
>>> Preparing source in /var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1 ...
 * Running eautoreconf in '/var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1' ...
 * Running autopoint --force ...                                         [ ok ]
 * Running libtoolize --install --copy --force --automake ...            [ ok ]
 * Running aclocal -I m4 ...                                             [ ok ]
 * Running autoconf --force ...                                          [ ok ]
 * Running autoheader ...                                                [ ok ]
 * Running automake --add-missing --copy --foreign --force-missing ...   [ ok ]
 * Running elibtoolize in: corebird-1.4.1/
 * Running elibtoolize in: corebird-1.4.1/build-aux/
 *   Applying portage/1.2.0 patch ...
 *   Applying sed/1.5.6 patch ...
 *   Applying as-needed/2.4.3 patch ...
 * Disabling deprecation warnings ...                                    [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1 ...
 * econf: updating corebird-1.4.1/build-aux/config.guess with /usr/share/gnuconfig/config.guess
 * econf: updating corebird-1.4.1/build-aux/config.sub with /usr/share/gnuconfig/config.sub
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/corebird-1.4.1 --htmldir=/usr/share/doc/corebird-1.4.1/html --libdir=/usr/lib64 --disable-maintainer-mode --disable-schemas-compile --disable-video
checking for a BSD-compatible install... /usr/lib/portage/python3.4/ebuild-helpers/xattr/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for x86_64-pc-linux-gnu-gcc... x86_64-pc-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-pc-linux-gnu-gcc accepts -g... yes
checking for x86_64-pc-linux-gnu-gcc option to accept ISO C89... none needed
checking whether x86_64-pc-linux-gnu-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of x86_64-pc-linux-gnu-gcc... none
checking for x86_64-pc-linux-gnu-gcc option to accept ISO C99... -std=gnu99
checking for x86_64-pc-linux-gnu-gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by x86_64-pc-linux-gnu-gcc -std=gnu99... /usr/x86_64-pc-linux-gnu/bin/ld
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/x86_64-pc-linux-gnu-nm -B
checking the name lister (/usr/bin/x86_64-pc-linux-gnu-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-linux-gnu/bin/ld option to reload object files... -r
checking for x86_64-pc-linux-gnu-objdump... x86_64-pc-linux-gnu-objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-pc-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-pc-linux-gnu-ar... x86_64-pc-linux-gnu-ar
checking for archiver @FILE support... @
checking for x86_64-pc-linux-gnu-strip... x86_64-pc-linux-gnu-strip
checking for x86_64-pc-linux-gnu-ranlib... x86_64-pc-linux-gnu-ranlib
checking command to parse /usr/bin/x86_64-pc-linux-gnu-nm -B output from x86_64-pc-linux-gnu-gcc -std=gnu99 object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for x86_64-pc-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... x86_64-pc-linux-gnu-gcc -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-pc-linux-gnu-gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for x86_64-pc-linux-gnu-gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if x86_64-pc-linux-gnu-gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if x86_64-pc-linux-gnu-gcc -std=gnu99 static flag -static works... yes
checking if x86_64-pc-linux-gnu-gcc -std=gnu99 supports -c -o file.o... yes
checking if x86_64-pc-linux-gnu-gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the x86_64-pc-linux-gnu-gcc -std=gnu99 linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for valac... /usr/bin/valac-0.32
checking whether /usr/bin/valac-0.32 is at least version 0.28.0... yes
checking for x86_64-pc-linux-gnu-pkg-config... /usr/bin/x86_64-pc-linux-gnu-pkg-config
checking pkg-config is at least version 0.16... yes
checking for CB... yes
checking for valac... (cached) /usr/bin/valac-0.32
checking whether /usr/bin/valac-0.32 is at least version 0.34.0... no
configure: WARNING: no proper vala compiler found
configure: WARNING: you will not be able to compile vala source files
checking for glib-compile-resources... /usr/bin/glib-compile-resources
checking for xmllint... /usr/bin/xmllint
checking GStreamer 1.0 element gtksink >= 1.0... found
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/gmsgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by x86_64-pc-linux-gnu-gcc -std=gnu99... /usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating data/Makefile
config.status: creating data/hicolor/Makefile
config.status: creating data/hicolor/256x256/Makefile
config.status: creating data/hicolor/128x128/Makefile
config.status: creating data/hicolor/96x96/Makefile
config.status: creating data/hicolor/64x64/Makefile
config.status: creating data/hicolor/48x48/Makefile
config.status: creating data/hicolor/32x32/Makefile
config.status: creating data/hicolor/24x24/Makefile
config.status: creating data/hicolor/16x16/Makefile
config.status: creating po/Makefile.in
config.status: creating tests/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
./configure: line 17648: valac: command not found

                Corebird  1.4.1
                  Prefix: /usr
           Vala Compiler: valac    --pkg gtk+-3.0   --pkg json-glib-1.0   --pkg rest-0.7   --pkg sqlite3   --pkg libsoup-2.4   --pkg glib-2.0   --target-glib=2.38 -D SPELLCHECK --pkg gspell-1
           valac version: 
              C Compiler: x86_64-pc-linux-gnu-gcc -std=gnu99 -O2 -pipe
               Debugging: no
          Video disabled: yes
      Gst check disabled: no
  Spellchecking disabled: no

>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1 ...
make -j3 
make  all-recursive
make[1]: Entering directory '/var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1'
Making all in src
make[2]: Entering directory '/var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1/src'
make[2]: valac: Command not found
Makefile:1206: recipe for target 'libcorebird_la_vala.stamp' failed
make[2]: *** [libcorebird_la_vala.stamp] Error 127
make[2]: Leaving directory '/var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1/src'
Makefile:443: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1'
Makefile:375: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: net-im/corebird-1.4.1::jorgicio failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-im/corebird-1.4.1::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=net-im/corebird-1.4.1::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/net-im/corebird-1.4.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-im/corebird-1.4.1/temp/environment'.
 * Working directory: '/var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1'
 * S: '/var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1'

>>> Failed to emerge net-im/corebird-1.4.1, Log file:

>>>  '/var/tmp/portage/net-im/corebird-1.4.1/temp/build.log'

 * Messages for package net-im/corebird-1.4.1:

 * ERROR: net-im/corebird-1.4.1::jorgicio failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-im/corebird-1.4.1::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=net-im/corebird-1.4.1::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/net-im/corebird-1.4.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-im/corebird-1.4.1/temp/environment'.
 * Working directory: '/var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1'
 * S: '/var/tmp/portage/net-im/corebird-1.4.1/work/corebird-1.4.1'

**Comment by jorgicio** [comment]
Which Vala version(s) are you using? You may do some clean, i.e. doing an `emerge --prune vala` and `emerge --depclean`

**Comment by Myu-Unix** [comment]
I'm using the amd64 stable 0.32.1, I'm all for using the 0.34.3 if needed by corebird-1.4.1 but in this case, shouldn't the corebird-1.4.1 pull it ?

**Comment by jorgicio** [comment]
Corebird depends on Vala 0.28 at least. Any version works. If there's not another package using more than one version of Vala, use the belonging version according your branch (if using stable or ~). Then, clean other versions and try again.
ie: I'm using stable version of vala and vala-common (0.32) and don't have any other. In your case, being stable, you can use something like: `emerge -C vala:0.34`

**Comment by Myu-Unix** [comment]
Hello !

So did some trial and errors but it seems I'm all clean regarding vala, `emerge -C vala:0.34` didn't changed anything, nor `emerge --prune vala`.

I recompiled it and it succeed but I don't have a `valac` binary installed, only "versioned" ones:    

   usr/bin/valac-0.32
   usr/bin/vapigen-0.32
   usr/bin/vapicheck-0.32
   usr/lib64/vala-0.32/gen-in

Which leads to :

~ # valac
-su: valac: command not found
~ # valac-0.32
No source file specified.

I think it's related/similar to this if that's of any help : [CMake fails to locate vala executable on Gentoo system #51](https://github.com/baedert/corebird/issues/51)

**Comment by jorgicio** [comment]
I thing corebird-1.4.2 fixes this issue.

**Comment by Myu-Unix** [comment]
Hello and thanks for the update !

I tried with 1.4.2 & vala 0.32 but no luck so far, the relevant lines are below.

```
checking for valac... /usr/bin/valac-0.32
checking whether /usr/bin/valac-0.32 is at least version 0.28.0... yes
checking for x86_64-pc-linux-gnu-pkg-config... /usr/bin/x86_64-pc-linux-gnu-pkg-config
checking pkg-config is at least version 0.16... yes
checking for CB... yes
checking for valac... (cached) /usr/bin/valac-0.32
checking whether /usr/bin/valac-0.32 is at least version 0.34.0... no
```

and a bit later : 

```
>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-im/corebird-1.4.2/work/corebird-1.4.2 ...
make -j3 
make  all-recursive
make[1]: Entering directory '/var/tmp/portage/net-im/corebird-1.4.2/work/corebird-1.4.2'
Making all in src
make[2]: Entering directory '/var/tmp/portage/net-im/corebird-1.4.2/work/corebird-1.4.2/src'
make[2]: valac: Command not found
make[2]: *** [Makefile:1206: libcorebird_la_vala.stamp] Error 127
make[2]: Leaving directory '/var/tmp/portage/net-im/corebird-1.4.2/work/corebird-1.4.2/src'
make[1]: *** [Makefile:443: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/net-im/corebird-1.4.2/work/corebird-1.4.2'
make: *** [Makefile:375: all] Error 2
 * ERROR: net-im/corebird-1.4.2::jorgicio failed (compile phase):
 *   emake failed
```

Cheers !

**Comment by jorgicio** [comment]
Hi! Try rebuilding vala, the symlink for the belonging version (ie, the valac command) is provided by the package itself.
`equery b /usr/bin/valac
dev-lang/vala-0.32.1 (/usr/bin/valac-0.32)`
Rebuild vala and try again.
`emerge -1 vala vala-common`

**Comment by Myu-Unix** [comment]
No more luck, here is directly fails at the compile phase : 

config.status: creating po/POTFILES
config.status: creating po/Makefile
./configure: line 17648: valac: command not found

                Corebird  1.4.2
                  Prefix: /usr
           Vala Compiler: valac    --pkg gtk+-3.0   --pkg json-glib-1.0   --pkg rest-0.7   --pkg sqlite3   --pkg libsoup-2.4   --pkg glib-2.0   --target-glib=2.38 -D SPELLCHECK --pkg gspell-1
           valac version: 
              C Compiler: x86_64-pc-linux-gnu-gcc -std=gnu99 -O2 -pipe
               Debugging: no
          Video disabled: yes
      Gst check disabled: no
  Spellchecking disabled: no

Should I try to symlink /usr/bin/valac-0.32 to /usr/bin/valac ? I can live with that if needed :)

**Comment by jorgicio** [comment]
The symlink may be the good option, but it must be provided by (re)installing vala, not doing by yourself. Anyways, try it ;)

**Comment by Myu-Unix** [comment]
Yes it works with that workaround. No clue why reinstalling valac does'nt provide me a valac symlink but as I said I can live with it. Rocking corebird 1.4.2 as of now :) 

Thank you for your help and dedication with this overlay !

**Comment by jorgicio** [comment]
Well, I did a clean vala instalation and it happens the same as you, so while there's no clear solution to this bug, I'll leave this issue open.

**Comment by jorgicio** [comment]
I found a very good solution: force make and configure to use the VALAC variable and some other musing. Tested here and working. Resync, reinstall and try again.

**Comment by Myu-Unix** [comment]
Indeed, I removed the symlink, resynced then retried and it now install itself gracefully ! Sweet, thanks for the update :)

**Comment by jorgicio** [comment]
No problem, you're welcome, so I'll close this ;)
