### ISSUE TITLE
app-office/onlyoffice is outdated, download checksum failed

### ISSUE THREAD

**Issue by optiz0r** [jorgicio/jorgicio-gentoo#86]
From what I can see on the website, the download links point to a static filename which is updated in-place every time a new version is released. Current download fails checksum because the ebuild version doesn't match the latest version on the website.

**Comment by jorgicio** [comment]
I noticed that, and I can't find an alternative link with the full source name. I upgraded the build.
Resync and try again.

**Comment by optiz0r** [comment]
Thanks. Our automation systems picked up this update last night and it has built successfully.
