### ISSUE TITLE
x11-themes/numix-frost-theme-3.6.6 fails to emerge

### ISSUE THREAD

**Issue by haarp** [jorgicio/jorgicio-gentoo#88]
>>> Install numix-frost-theme-3.6.6 into /var/tmp/portage/x11-themes/numix-frost-theme-3.6.6/image/ category x11-themes
    make -j8 DESTDIR=/var/tmp/portage/x11-themes/numix-frost-theme-3.6.6/image/ install 
    rm -rf dist/Numix-Frost-3.6.6
    rm -f src/toolkits/gtk-3.0/gtk.gresource src/toolkits/gtk-3.20/gtk.gresource
    rm -f src/desktops/gnome-shell/gnome-shell.gresource
    mkdir -p dist/Numix-Frost-3.6.6/gtk-3.0 dist/Numix-Frost-3.6.6/gtk-3.20 dist/Numix-Frost-3.6.6/cinnamon dist/Numix-Frost-3.6.6/gnome-shell
    rm -rf src/toolkits/gtk-3.0/dist src/toolkits/gtk-3.20/dist src/desktops/cinnamon/dist
    scss --update --sourcemap=none src/toolkits/gtk-3.0/scss:src/toolkits/gtk-3.0/dist
      directory src/toolkits/gtk-3.0/dist
          write src/toolkits/gtk-3.0/dist/gtk-dark.css
          write src/toolkits/gtk-3.0/dist/gtk.css
    scss --update --sourcemap=none src/toolkits/gtk-3.20/scss:src/toolkits/gtk-3.20/dist
      directory src/toolkits/gtk-3.20/dist
          write src/toolkits/gtk-3.20/dist/gtk-dark.css
          write src/toolkits/gtk-3.20/dist/gtk.css
    scss --update --sourcemap=none src/desktops/cinnamon/scss:src/desktops/cinnamon/dist
      directory src/desktops/cinnamon/dist
          write src/desktops/cinnamon/dist/cinnamon.css
    cp -t dist/Numix-Frost-3.6.6/gtk-3.0 src/toolkits/gtk-3.0/{*.css,*.png}
    cp -t dist/Numix-Frost-3.6.6/gtk-3.20 src/toolkits/gtk-3.20/{*.css,*.png,*.theme}
    cp -t dist/Numix-Frost-3.6.6/cinnamon src/desktops/cinnamon/dist/*.css src/desktops/cinnamon/{*.json,*.png}
    cp -t dist/Numix-Frost-3.6.6/gnome-shell src/desktops/gnome-shell/*.*
    glib-compile-resources --sourcedir=src/toolkits/gtk-3.0 src/toolkits/gtk-3.0/gtk.gresource.xml
    glib-compile-resources --sourcedir=src/toolkits/gtk-3.20 src/toolkits/gtk-3.20/gtk.gresource.xml
    mv src/toolkits/gtk-3.0/gtk.gresource dist/Numix-Frost-3.6.6/gtk-3.0
    mv src/toolkits/gtk-3.20/gtk.gresource dist/Numix-Frost-3.6.6/gtk-3.20
    /bin/sh: -c: line 0: unexpected EOF while looking for matching `''
    /bin/sh: -c: line 1: syntax error: unexpected end of file
    make: *** [Makefile:66: install] Error 1

**Comment by jorgicio** [comment]
Hi.
I noticed the bug is in upstream, so while I can find a fix to that, I'll mask that version. Please, try with a previous version, i.e. 3.6.5.

**Comment by haarp** [comment]
Indeed, 3.6.5 seems to work. Thanks!

**Comment by jorgicio** [comment]
You're welcome, so while I can find a solution for that, I'll leave open this issue.

**Comment by haarp** [comment]
I suspect that the problem is sh. It should be using bash.

in the Makefile, you can replace

    install: all
        @$(SHELL_EXPORT) $(UTILS) install

with

    install: all
        $(UTILS) install $(INSTALL_DIR)

This gets you further but fails at another point.

**Comment by jorgicio** [comment]
I noticed that the problem is in upstream. I tried reworking the sources, but I found that it's useless because even with recent commits,  it fails at build, so I decided to unpack the theme from the Antergos repos and install already compiled.
Try again, now I unmasked that version.

**Comment by jorgicio** [comment]
As I see no response (and I fixed the package), I'll close this issue. Feel free to reopen if there are some problems.
