### ISSUE TITLE
atom-bin-1.17.0 fperms fails because it can't find ctags-linux from the symbols-view package

### ISSUE THREAD

**Issue by simonvanderveldt** [jorgicio/jorgicio-gentoo#89]
```
>>> Install atom-bin-1.17.0 into /var/tmp/portage/app-editors/atom-bin-1.17.0/image/ category app-editors
 * PT_PAX marking -m atom with scanelf
 * XATTR_PAX marking -me atom with setfattr
chmod: cannot access '/var/tmp/portage/app-editors/atom-bin-1.17.0/image//usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-linux': No such file or directory
 * ERROR: app-editors/atom-bin-1.17.0::jorgicio failed (install phase):
 *   fperms failed
```

Caused by
https://github.com/jorgicio/jorgicio-gentoo/blob/ff41c3f78961b08c68fce2f271fc91c278ed36c3/app-editors/atom-bin/atom-bin-1.17.0.ebuild#L97

`ctag-linux` from the symbols view package can actually be found in `resources/app/node_modules/symbols-view/vendor/ctags-linux`.

**Comment by jorgicio** [comment]
Alright, I just fixed that line. Please resync and try again and tell me what about that.

**Comment by simonvanderveldt** [comment]
@jorgicio it works :)
Thanks for the quick fix!
