### ISSUE TITLE
Deepin for gentoo

### ISSUE THREAD

**Issue by talesam** [jorgicio/jorgicio-gentoo#9]
Hello! You know the Deepin desktop, built in html5? It is super light, simple and functional ... You would be able or know of someone who concierge him to gentoo?

Here the packages are, few !!
https://github.com/linuxdeepin

Hugs!

**Comment by jorgicio** [comment]
Well... there's already an overlay with all deepin-related packages. Add the overlay gentoo-zh (from China), and you're done.

Greetings!

**Comment by talesam** [comment]
Are you sure you have all the packages? I just thought a 5
