### ISSUE TITLE
Haguichi is switching build system

### ISSUE THREAD

**Issue by ztefn** [jorgicio/jorgicio-gentoo#93]
Hi there!

As uber cool upstream I'd like to personally and readily inform you that Haguichi master has just [switched from CMake to Meson](https://github.com/ztefn/haguichi/commit/34227202157ce34e99d892ed589e0b4c80457505).

This means that the package [net-vpn/haguichi/haguichi-9999](https://github.com/jorgicio/jorgicio-gentoo/blob/master/net-vpn/haguichi/haguichi-9999.ebuild) will need to be changed as of this moment. Next release (v1.3.8) will be using Meson too, obviously!

And by the way, thanks for providing these well maintained Haguichi ebuilds to Gentoo users! Let me know if you have some clear instructions I can publish on the [Haguichi website](https://www.haguichi.net/) to point Gentoo users to your overlay.

Cheers! =)

**Comment by ztefn** [comment]
PS: Forgot the most important part, the [new build and install instructions](https://github.com/ztefn/haguichi/blob/master/INSTALL.md).

**Comment by jorgicio** [comment]
Hello, @ztefn, thanks for your advice and your kind words.

To be honest, it's the first time I heard about Meson, so I had to do kinda research about that and I noticed that's not so hard to implement it, so I'll do it then with the 9999 ebuild of Haguichi.

Also, the instructions are available in the main page of this overlay, but by the way, I'll leave them here:

Install layman first if not available (the USE="git" is enabled by default):

`emerge layman`

then, add my overlay:
`layman -a jorgicio`

and then, install Haguichi (its dependencies are coming too):
`emerge net-vpn/haguichi`

I hope this is clear. Meanwhile, I'll do the rework to the package.

Thanks again. Stay tuned when I leave that ebuild ready to install ;)

**Comment by jorgicio** [comment]
Good news: 9999 ebuild of Haguichi was updated, tested and worked successfully.
I'll be waiting to the 1.3.8 version then ;)

Thanks again!

**Comment by ztefn** [comment]
Superb, thank you!

Indeed DESTDIR can be set as environment variable for ninja to use, like:
DESTDIR="$pkgdir" ninja install

The [download page](https://www.haguichi.net/download/) on haguichi.net is now accomodated with a Gentoo section with link to the main page of this overlay and direct link to the usage instructions.

Cheers!

**Comment by jorgicio** [comment]
Hi, I had to find it out my myself, and yes, I also applied the DESTDIR variable, as well as some others like MAKE and stuff.

And thanks for the instructions ;)

Cheers!

**Comment by ztefn** [comment]
@jorgicio I tried to follow your instructions on a Gentoo LiveDVD. Adding to overlay seems to work, but installing the package doesn't:

```bash
gentoo@livecd ~ $ emerge layman
emerge: superuser access is required
gentoo@livecd ~ $ sudo emerge layman
Calculating dependencies         ... done!                   

>>> Verifying ebuild manifests
>>> Running pre-merge checks for app-portage/layman-2.4.1-r1

>>> Emerging (1 of 1) app-portage/layman-2.4.1-r1::gentoo
[cut enormous logging]
>>> Completed installing layman-2.4.1-r1 into /var/tmp/portage/app-portage/layman-2.4.1-r1/image/

 * Final size of build directory: 1572 KiB
 * Final size of installed tree: 2228 KiB

ecompressdir: bzip2 -9 /usr/share/man
ecompressdir: bzip2 -9 /usr/share/doc

>>> Installing (1 of 1) app-portage/layman-2.4.1-r1::gentoo
 * Removing /usr/share/doc
 * Running layman-updater...
 *   Automatic db rename: db already updated: /var/lib/layman/installed.xml
 * 
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.
gentoo@livecd ~ $ sudo layman -a jorgicio

 * Adding overlay...
 * Overlay "jorgicio" is not official. Continue installing? [y/n]: y
 * Running Git... # ( cd /var/lib/layman  && /usr/bin/git clone https://github.com/jorgicio/jorgicio-gentoo.git /var/lib/layman/jorgicio )
Cloning into '/var/lib/layman/jorgicio'...
remote: Counting objects: 11497, done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 11497 (delta 37), reused 77 (delta 19), pack-reused 11377
Receiving objects: 100% (11497/11497), 4.41 MiB | 1.62 MiB/s, done.
Resolving deltas: 100% (5823/5823), done.
Checking connectivity... done.
 * Running Git... # ( cd /var/lib/layman/jorgicio  && /usr/bin/git config user.name "layman" )
 * Running Git... # ( cd /var/lib/layman/jorgicio  && /usr/bin/git config user.email "layman@localhost" )
 * Successfully added overlay(s) jorgicio.

gentoo@livecd ~ $ sudo emerge net-vpn/haguichi
Calculating dependencies                                  n
!!! 'net-vpn/haguichi' has a category that is not listed in /etc/portage/categories
... done!

emerge: there are no ebuilds to satisfy "net-vpn/haguichi".

emerge: searching for similar names...
emerge: Maybe you meant any of these: net-dns/cagibi, net-print/magicfilter, net-dns/avahi?
gentoo@livecd ~ $
```

**Comment by jorgicio** [comment]
Ok, I think the culprit was the repo_name file removed, so please, resync with `emaint sync -r jorgicio` and try again.

**Comment by ztefn** [comment]
No difference.

**Comment by jorgicio** [comment]
Try what's going on when you search that package:
`emerge --sync haguichi`

**Comment by ztefn** [comment]
!!! Unknown repo(s): haguichi

**Comment by ztefn** [comment]
Using --search instead of --sync it finds only x11-plugins/haguichi-indicator

**Comment by ztefn** [comment]
Isn't the problem is this error: `'net-vpn/haguichi' has a category that is not listed in /etc/portage/categories` ?

**Comment by jorgicio** [comment]
Mmmm... did you sync the Portage tree first?
`emaint sync -A`

**Comment by ztefn** [comment]
Nope, I had not done anything that is not in the instructions... but that sync command seems to do the trick! The `emerge --search` command now finds Haguichi 1.3.7 which I have now emerged.

How can I emerge version 9999?

**Comment by jorgicio** [comment]
As being a fresh installation (or live CD), the first and elemental thing to do is sync the official included repos (and it applies to all distributions), so that's what I haven't mentioned before. Anyways, I'm glad that worked ;)
For the 9999 version, first you must create a directory called "package.accept_keywords" inside `/etc/portage`:
`mkdir /etc/portage/package.accept_keywords`
Then, inside it, create a file with the editor you want and the name you want. Inside that file, add this line:
`net-vpn/haguichi **`
And then install it and you're done.

**Comment by ztefn** [comment]
Thanks.

`/etc/portage/package.accept_keywords` appeared to be text file itself already, to which I could add the line `=net-vpn/haguichi-9999 **` in order to successfully emerge version 9999.

**Comment by jorgicio** [comment]
That can be a file, indeed, but some packages suggest to use it as a directory, but it works anyways. I'm glad you emerged the package successfully.

**Comment by ztefn** [comment]
Just a quick reminder, version 1.3.8 [has been released](https://www.haguichi.net/news/release138/)! =)

**Comment by ztefn** [comment]
And while I'm at it... Also haguichi-indicator version 0.3.4, which too is using Meson as build system.

**Comment by jorgicio** [comment]
Thank you for the reminder. Now this is updated.
And thank you for the project ;)
