### ISSUE TITLE
visual-studio-code does startup the wrong executable

### ISSUE THREAD

**Issue by NobbZ** [jorgicio/jorgicio-gentoo#94]
Because I had trouble setting up my GO-Envorinment on the fly I filed a bug at the VSCode go-plugin, but after some analysis we found that the real culprit seems to be that the wrong executable is started.

According to Microsoft/vscode-go#1075 `/opt/visual-studio-code/bin/code` needs to be run instead of `/opt/visual-studio-code/code` by your wrapper script.

I've also analyzed how it is done on ubuntu. there is a simlink to exactly that wrapper script put into the path. Perhaps you can do a link as well instead of creating just another wrapper script?

**Comment by NobbZ** [comment]
I am back home and was able to check it if changing the script would actually help with my problem.

It actually does. After I made `/opt/visual-studio-code/bin/code` executable, `GOPATH=$(pwd)/go /opt/visual-studio-code/bin/code` worked like a charm and I was able see my terminals environment in the newly opened vscode.

**Comment by jorgicio** [comment]
Got it, thanks for the PR ;)
