### ISSUE TITLE
VidCutter complains PyQt distribution doesn't exist but PyQt does exist

### ISSUE THREAD

**Issue by taohansen** [jorgicio/jorgicio-gentoo#96]
VidCutter complains PyQt distribution doesn't exist but PyQt does exist

**Comment by jorgicio** [comment]
Hi, can you post a log file to check it, please?

**Comment by jorgicio** [comment]
My bad, I tried here and I found the culprit. It was in the src_prepare. Fixed and now working.
Resync and try again.
