### ISSUE TITLE
media-gfx/peruse broken: depends on moved package

### ISSUE THREAD

**Issue by NHOrus** [jorgicio/jorgicio-gentoo#98]
kio-extras moved from kde-frameworks to kde-apps

**Comment by jorgicio** [comment]
Ok, ebuild fixed. Try again and tell me what's going on, please.

**Comment by NHOrus** [comment]
That fixed dependency problem.
Emerging.
Will report if it succeeds or fails.

**Comment by NHOrus** [comment]
Broken, but differently now:

```
>>> Source unpacked in /var/tmp/portage/media-gfx/peruse-1.2/work
 * ERROR: media-gfx/peruse-1.2::jorgicio failed (prepare phase):
 *   The source directory '/var/tmp/portage/media-gfx/peruse-1.2/work/peruse-1.2' doesn't exist
```
```
ls /var/tmp/portage/media-gfx/peruse-1.2/work 
peruse
```

**Comment by NHOrus** [comment]
And next error after manually working around previous one is 
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: Declarative) (found suitable version "5.36.0",
  minimum required is "5.5")
```

**Comment by NHOrus** [comment]
After that, next error is runtime one:
```
Failed to load the component from disk. Reported error was: "file:///usr/share/peruse/qml/Main.qml:24 module \"QtQuick.Dialogs\" is not installed\n"
```

**Comment by NHOrus** [comment]
That's fixed by installing qtquickcontrols

**Comment by jorgicio** [comment]
Ok, thanks for the reports. Sorry for the late response, I was in bed.
I'll fix it now.

**Comment by NHOrus** [comment]
Well, if bug is to be fixed, it's better to be fixed all the way.
And no problem.

Thank you for both fixing this bug and providing ebuild of VS Code.

**Comment by jorgicio** [comment]
Ok, I think the issue is fixed. Please, try again and tell me what's going on.
Ebuild updated.
And you're welcome ;)

**Comment by NHOrus** [comment]
In ten to fifteen hours I will.

**Comment by jorgicio** [comment]
Ok, no problem, sorry if it takes you too much time :)

**Comment by NHOrus** [comment]
Everything is fixed.
Thank you.
