### ISSUE TITLE
dev-libs/kirigami moved to kde-frameworks/kirigami

### ISSUE THREAD

**Issue by NHOrus** [jorgicio/jorgicio-gentoo#99]
So, now peruse doesn't build, again, and possibly others.

**Comment by jorgicio** [comment]
Ok, ebuild fixed. I hope this solve this issue.

**Comment by NHOrus** [comment]
Somehow, it's either tries to use -5.37.0 or -9999 version of kirigami, instead of -2.
As one is keyworded and other is masked and labeled as unreleased in scripts, I don't kinda want to try this right now.
Thank you again.

**Comment by jorgicio** [comment]
Ok, dependency fixed. Please, try again.

**Comment by NHOrus** [comment]
Can do tomorrow only, sorry.

**Comment by jorgicio** [comment]
Ok, no problem. However, you can do a quick test using the `--pretend` option:
`emerge --pretend peruse`

**Comment by NHOrus** [comment]
At runtime, it needs kirigumi-1.1.0, not 2. Sorry for misinformation. Everything else works.

**Comment by NHOrus** [comment]
I hope it should just work now for people until next breakage, but sadly I must part ways with it.

At least until it hits KDE as part of DE.

**Comment by jorgicio** [comment]
Well, as Peruse depends on the KDE Frameworks, it become kinda messy, but don't worry, better try it when using KDE (I hope to do it soon, meanwhile, I use MATE as DE)

**Comment by NHOrus** [comment]
MATE here. My main gripe with both it and Atril is that they refuse to open zips, but open same zips full of images when they are renamed to cbz... Stupid.
